### ISSUE TITLE
Use `eyre::Report` to get context for error from API calls

### ISSUE THREAD

**Issue by grtlr** [iotaledger/inx-chronicle#901]
Ideally we would have access to the endpoint and query parameters in the logs.

**Comment by Alexandcoats** [comment]
Unfortunately, this does not seem to be straightforward. Firstly, `eyre` is not compatible with the API because of the need to specify an error code. Secondly, the URI/query params come from the request and cannot, as far as I can tell, be easily added to the response in a single place. They would have to be manually extracted from the request and added to every error at the creation site. However, the URI at least is noted by `tower_http::trace`, so if we get jaeger or whatever working, we should be able to find that information and associate it with internal errors.
